--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Client; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Client" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "Cpf" text NOT NULL,
    "Phone" text NOT NULL,
    "Email" text NOT NULL,
    "Street" text NOT NULL,
    "Number" text NOT NULL,
    "Neighborhood" text NOT NULL,
    "City" text NOT NULL,
    "Uf" text NOT NULL,
    "UserId" integer
);


ALTER TABLE public."Client" OWNER TO postgres;

--
-- Name: Client_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Client" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Client_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Contract; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Contract" (
    "Id" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "DependentCount" integer NOT NULL,
    "ClientId" integer,
    "FuneralPlansId" integer
);


ALTER TABLE public."Contract" OWNER TO postgres;

--
-- Name: Contract_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Contract" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contract_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    id integer NOT NULL,
    cpfcnpj character varying(14) NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(50) NOT NULL,
    phone character varying(13) NOT NULL,
    street character varying(100) NOT NULL,
    number character varying(10) NOT NULL,
    neighborhood character varying(60) NOT NULL,
    city character varying(60) NOT NULL,
    uf character varying(2) NOT NULL
);


ALTER TABLE public.company OWNER TO postgres;

--
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cremation; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cremation (
    id integer NOT NULL,
    date date NOT NULL,
    "time" time without time zone NOT NULL,
    cremationnumber text NOT NULL,
    "DeceasedPersonId" integer NOT NULL
);


ALTER TABLE public.cremation OWNER TO postgres;

--
-- Name: cremation_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cremation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cremation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: deceasedperson; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deceasedperson (
    id integer NOT NULL,
    name text NOT NULL,
    age integer NOT NULL,
    birthday date NOT NULL,
    deathcause text NOT NULL,
    nationality text NOT NULL,
    marital integer NOT NULL,
    sex integer NOT NULL,
    "WakeId" integer,
    "ClientId" integer
);


ALTER TABLE public.deceasedperson OWNER TO postgres;

--
-- Name: deceasedperson_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deceasedperson ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deceasedperson_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dependent; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dependent (
    id integer NOT NULL,
    name text NOT NULL,
    cpf text NOT NULL,
    "ContractId" integer
);


ALTER TABLE public.dependent OWNER TO postgres;

--
-- Name: dependent_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dependent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dependent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funeral; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funeral (
    id integer NOT NULL,
    date date NOT NULL,
    location character varying(150) NOT NULL,
    starttime integer NOT NULL,
    endtime integer NOT NULL,
    description text NOT NULL,
    "UserId" integer
);


ALTER TABLE public.funeral OWNER TO postgres;

--
-- Name: funeral_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funeral ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.funeral_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: funeralplans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.funeralplans (
    "Id" integer NOT NULL,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "AnnualValue" numeric(18,2) NOT NULL,
    available boolean NOT NULL,
    "MaxDependents" integer NOT NULL,
    "MaxAge" integer NOT NULL,
    "dependentAdditional " numeric(18,2) NOT NULL,
    "CompanyId" integer
);


ALTER TABLE public.funeralplans OWNER TO postgres;

--
-- Name: funeralplans_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.funeralplans ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."funeralplans_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: thanatopraxia; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.thanatopraxia (
    id text NOT NULL,
    date date NOT NULL,
    description text NOT NULL,
    conditionbody text NOT NULL,
    "UserId" integer,
    "DeceasedPersonId" integer NOT NULL
);


ALTER TABLE public.thanatopraxia OWNER TO postgres;

--
-- Name: transport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transport (
    id integer NOT NULL,
    name text NOT NULL,
    data date NOT NULL,
    "time" time without time zone NOT NULL,
    street text NOT NULL,
    number text NOT NULL,
    neighborhood text NOT NULL,
    city text NOT NULL,
    uf text NOT NULL,
    "DeceasedPersonId" integer
);


ALTER TABLE public.transport OWNER TO postgres;

--
-- Name: transport_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transport ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transport_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    name character varying(100) NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    cpf character varying(11),
    phone text,
    typeemployee integer NOT NULL,
    userstatus integer NOT NULL,
    hiredate date,
    "CompanyId" integer
);


ALTER TABLE public."user" OWNER TO postgres;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Client; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Client" ("Id", "Name", "Cpf", "Phone", "Email", "Street", "Number", "Neighborhood", "City", "Uf", "UserId") FROM stdin;
\.


--
-- Data for Name: Contract; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Contract" ("Id", "IsActive", "StartDate", "EndDate", "DependentCount", "ClientId", "FuneralPlansId") FROM stdin;
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250520105305_database	9.0.3
\.


--
-- Data for Name: company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company (id, cpfcnpj, name, email, phone, street, number, neighborhood, city, uf) FROM stdin;
\.


--
-- Data for Name: cremation; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cremation (id, date, "time", cremationnumber, "DeceasedPersonId") FROM stdin;
\.


--
-- Data for Name: deceasedperson; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.deceasedperson (id, name, age, birthday, deathcause, nationality, marital, sex, "WakeId", "ClientId") FROM stdin;
\.


--
-- Data for Name: dependent; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.dependent (id, name, cpf, "ContractId") FROM stdin;
\.


--
-- Data for Name: funeral; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.funeral (id, date, location, starttime, endtime, description, "UserId") FROM stdin;
\.


--
-- Data for Name: funeralplans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.funeralplans ("Id", "Name", "Description", "AnnualValue", available, "MaxDependents", "MaxAge", "dependentAdditional ", "CompanyId") FROM stdin;
\.


--
-- Data for Name: thanatopraxia; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.thanatopraxia (id, date, description, conditionbody, "UserId", "DeceasedPersonId") FROM stdin;
\.


--
-- Data for Name: transport; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transport (id, name, data, "time", street, number, neighborhood, city, uf, "DeceasedPersonId") FROM stdin;
\.


--
-- Data for Name: user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."user" (id, name, email, password, cpf, phone, typeemployee, userstatus, hiredate, "CompanyId") FROM stdin;
1	giorno	giorno@gmail.com	15e2b0d3c33891ebb0f1ef609ec419420c20e320ce94c65fbc8c3312448eb225	\N	\N	0	0	\N	\N
\.


--
-- Name: Client_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Client_Id_seq"', 1, false);


--
-- Name: Contract_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Contract_Id_seq"', 1, false);


--
-- Name: company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.company_id_seq', 1, false);


--
-- Name: cremation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cremation_id_seq', 1, false);


--
-- Name: deceasedperson_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.deceasedperson_id_seq', 1, false);


--
-- Name: dependent_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dependent_id_seq', 1, false);


--
-- Name: funeral_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.funeral_id_seq', 1, false);


--
-- Name: funeralplans_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."funeralplans_Id_seq"', 1, false);


--
-- Name: transport_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transport_id_seq', 1, false);


--
-- Name: user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.user_id_seq', 1, true);


--
-- Name: Client PK_Client; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "PK_Client" PRIMARY KEY ("Id");


--
-- Name: Contract PK_Contract; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contract"
    ADD CONSTRAINT "PK_Contract" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: company PK_company; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT "PK_company" PRIMARY KEY (id);


--
-- Name: cremation PK_cremation; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cremation
    ADD CONSTRAINT "PK_cremation" PRIMARY KEY (id);


--
-- Name: deceasedperson PK_deceasedperson; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deceasedperson
    ADD CONSTRAINT "PK_deceasedperson" PRIMARY KEY (id);


--
-- Name: dependent PK_dependent; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dependent
    ADD CONSTRAINT "PK_dependent" PRIMARY KEY (id);


--
-- Name: funeral PK_funeral; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funeral
    ADD CONSTRAINT "PK_funeral" PRIMARY KEY (id);


--
-- Name: funeralplans PK_funeralplans; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funeralplans
    ADD CONSTRAINT "PK_funeralplans" PRIMARY KEY ("Id");


--
-- Name: thanatopraxia PK_thanatopraxia; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thanatopraxia
    ADD CONSTRAINT "PK_thanatopraxia" PRIMARY KEY (id);


--
-- Name: transport PK_transport; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT "PK_transport" PRIMARY KEY (id);


--
-- Name: user PK_user; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "PK_user" PRIMARY KEY (id);


--
-- Name: IX_Client_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Client_UserId" ON public."Client" USING btree ("UserId");


--
-- Name: IX_Contract_ClientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Contract_ClientId" ON public."Contract" USING btree ("ClientId");


--
-- Name: IX_Contract_FuneralPlansId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Contract_FuneralPlansId" ON public."Contract" USING btree ("FuneralPlansId");


--
-- Name: IX_cremation_DeceasedPersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_cremation_DeceasedPersonId" ON public.cremation USING btree ("DeceasedPersonId");


--
-- Name: IX_deceasedperson_ClientId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_deceasedperson_ClientId" ON public.deceasedperson USING btree ("ClientId");


--
-- Name: IX_deceasedperson_WakeId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_deceasedperson_WakeId" ON public.deceasedperson USING btree ("WakeId");


--
-- Name: IX_dependent_ContractId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_dependent_ContractId" ON public.dependent USING btree ("ContractId");


--
-- Name: IX_funeral_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_funeral_UserId" ON public.funeral USING btree ("UserId");


--
-- Name: IX_funeralplans_CompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_funeralplans_CompanyId" ON public.funeralplans USING btree ("CompanyId");


--
-- Name: IX_thanatopraxia_DeceasedPersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_thanatopraxia_DeceasedPersonId" ON public.thanatopraxia USING btree ("DeceasedPersonId");


--
-- Name: IX_thanatopraxia_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_thanatopraxia_UserId" ON public.thanatopraxia USING btree ("UserId");


--
-- Name: IX_transport_DeceasedPersonId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_transport_DeceasedPersonId" ON public.transport USING btree ("DeceasedPersonId");


--
-- Name: IX_user_CompanyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_user_CompanyId" ON public."user" USING btree ("CompanyId");


--
-- Name: Client FK_Client_user_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Client"
    ADD CONSTRAINT "FK_Client_user_UserId" FOREIGN KEY ("UserId") REFERENCES public."user"(id);


--
-- Name: Contract FK_Contract_Client_ClientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contract"
    ADD CONSTRAINT "FK_Contract_Client_ClientId" FOREIGN KEY ("ClientId") REFERENCES public."Client"("Id");


--
-- Name: Contract FK_Contract_funeralplans_FuneralPlansId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Contract"
    ADD CONSTRAINT "FK_Contract_funeralplans_FuneralPlansId" FOREIGN KEY ("FuneralPlansId") REFERENCES public.funeralplans("Id");


--
-- Name: cremation FK_cremation_deceasedperson_DeceasedPersonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cremation
    ADD CONSTRAINT "FK_cremation_deceasedperson_DeceasedPersonId" FOREIGN KEY ("DeceasedPersonId") REFERENCES public.deceasedperson(id) ON DELETE CASCADE;


--
-- Name: deceasedperson FK_deceasedperson_Client_ClientId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deceasedperson
    ADD CONSTRAINT "FK_deceasedperson_Client_ClientId" FOREIGN KEY ("ClientId") REFERENCES public."Client"("Id");


--
-- Name: deceasedperson FK_deceasedperson_funeral_WakeId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.deceasedperson
    ADD CONSTRAINT "FK_deceasedperson_funeral_WakeId" FOREIGN KEY ("WakeId") REFERENCES public.funeral(id);


--
-- Name: dependent FK_dependent_Contract_ContractId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dependent
    ADD CONSTRAINT "FK_dependent_Contract_ContractId" FOREIGN KEY ("ContractId") REFERENCES public."Contract"("Id");


--
-- Name: funeral FK_funeral_user_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funeral
    ADD CONSTRAINT "FK_funeral_user_UserId" FOREIGN KEY ("UserId") REFERENCES public."user"(id);


--
-- Name: funeralplans FK_funeralplans_company_CompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.funeralplans
    ADD CONSTRAINT "FK_funeralplans_company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES public.company(id);


--
-- Name: thanatopraxia FK_thanatopraxia_deceasedperson_DeceasedPersonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thanatopraxia
    ADD CONSTRAINT "FK_thanatopraxia_deceasedperson_DeceasedPersonId" FOREIGN KEY ("DeceasedPersonId") REFERENCES public.deceasedperson(id) ON DELETE CASCADE;


--
-- Name: thanatopraxia FK_thanatopraxia_user_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.thanatopraxia
    ADD CONSTRAINT "FK_thanatopraxia_user_UserId" FOREIGN KEY ("UserId") REFERENCES public."user"(id);


--
-- Name: transport FK_transport_deceasedperson_DeceasedPersonId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT "FK_transport_deceasedperson_DeceasedPersonId" FOREIGN KEY ("DeceasedPersonId") REFERENCES public.deceasedperson(id);


--
-- Name: user FK_user_company_CompanyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "FK_user_company_CompanyId" FOREIGN KEY ("CompanyId") REFERENCES public.company(id);


--
-- PostgreSQL database dump complete
--

