// <auto-generated />
using System;
using LumenSys.WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LumenSys.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("City");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Email");

                    b.Property<int?>("FuneralPlansId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Neighborhood");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Phone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Street");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Uf");

                    b.HasKey("Id");

                    b.HasIndex("FuneralPlansId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("CpfCnpj")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpfcnpj");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Cremation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DeceasedPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cremationnumber");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedPersonId")
                        .IsUnique();

                    b.ToTable("cremation");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.DeceasedPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("DeathCause")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("deathcause");

                    b.Property<int>("Marital")
                        .HasColumnType("integer")
                        .HasColumnName("marital");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nationality");

                    b.Property<int>("Sex")
                        .HasColumnType("integer")
                        .HasColumnName("sex");

                    b.Property<int?>("WakeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WakeId");

                    b.ToTable("deceasedperson");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("dependent");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("email");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date")
                        .HasColumnName("hiredate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.FuneralPlans", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double>("MonthlyValue")
                        .HasColumnType("double precision")
                        .HasColumnName("monthlyvalue");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("TypePlanId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypePlanId");

                    b.ToTable("funeralplans");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Thanatopraxia", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConditionBody")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditionbody");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("DeceasedPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedPersonId")
                        .IsUnique();

                    b.HasIndex("EmployeeId");

                    b.ToTable("thanatopraxia");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<int?>("DeceasedPersonId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("neighborhood");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("DeceasedPersonId");

                    b.ToTable("transport");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.TypePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("typeplan");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.TypeWake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("typewake");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Wake", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("EndTime")
                        .HasColumnType("integer")
                        .HasColumnName("endtime");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<int>("StartTime")
                        .HasColumnType("integer")
                        .HasColumnName("starttime");

                    b.Property<int>("TypeWakeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TypeWakeId");

                    b.ToTable("wake");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("TypeEmployee")
                        .HasColumnType("integer")
                        .HasColumnName("typeemployee");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer")
                        .HasColumnName("userstatus");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Client", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.FuneralPlans", "FuneralPlans")
                        .WithMany("client")
                        .HasForeignKey("FuneralPlansId");

                    b.Navigation("FuneralPlans");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Cremation", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.DeceasedPerson", "DeceasedPerson")
                        .WithOne("Cremation")
                        .HasForeignKey("LumenSys.WebAPI.Objects.Models.Cremation", "DeceasedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeceasedPerson");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.DeceasedPerson", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.Client", "Client")
                        .WithMany("deceasedPerson")
                        .HasForeignKey("ClientId");

                    b.HasOne("LumenSys.WebAPI.Objects.Models.Wake", "Wake")
                        .WithMany("DeceasedPerson")
                        .HasForeignKey("WakeId");

                    b.Navigation("Client");

                    b.Navigation("Wake");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Dependent", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.Client", "client")
                        .WithMany("dependent")
                        .HasForeignKey("ClientId");

                    b.Navigation("client");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Employee", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.Company", "company")
                        .WithMany("employee")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("company");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.FuneralPlans", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.TypePlan", "TypePlan")
                        .WithMany("FuneralPlan")
                        .HasForeignKey("TypePlanId");

                    b.Navigation("TypePlan");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Thanatopraxia", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.DeceasedPerson", "deceasedPerson")
                        .WithOne("Thanatopraxia")
                        .HasForeignKey("LumenSys.WebAPI.Objects.Models.Thanatopraxia", "DeceasedPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LumenSys.WebAPI.Objects.Models.Employee", "Employee")
                        .WithMany("thanatopraxia")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");

                    b.Navigation("deceasedPerson");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Transport", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.DeceasedPerson", "DeceasedPerson")
                        .WithMany("Transport")
                        .HasForeignKey("DeceasedPersonId");

                    b.Navigation("DeceasedPerson");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Wake", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.TypeWake", "TypeWake")
                        .WithMany("Wake")
                        .HasForeignKey("TypeWakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeWake");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.User", b =>
                {
                    b.HasOne("LumenSys.WebAPI.Objects.Models.Employee", "Employee")
                        .WithMany("Users")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Client", b =>
                {
                    b.Navigation("deceasedPerson");

                    b.Navigation("dependent");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Company", b =>
                {
                    b.Navigation("employee");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.DeceasedPerson", b =>
                {
                    b.Navigation("Cremation");

                    b.Navigation("Thanatopraxia")
                        .IsRequired();

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Employee", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("thanatopraxia");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.FuneralPlans", b =>
                {
                    b.Navigation("client");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.TypePlan", b =>
                {
                    b.Navigation("FuneralPlan");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.TypeWake", b =>
                {
                    b.Navigation("Wake");
                });

            modelBuilder.Entity("LumenSys.WebAPI.Objects.Models.Wake", b =>
                {
                    b.Navigation("DeceasedPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
